### ISSUE TITLE
Add db_create_dsm_table() 

### ISSUE THREAD

**Issue by Aeilert** [PIP-Technical-Team/pipdm#17]
Hi @randrescastaneda ,

Could you take the functions you have in the pipeline ingestion repo and add them here to create the survey mean table. 

The structure in the current `deflated_svy_means.fst` is mostly what we need, but I have the following suggestions for the final output: 

- Make sure `surveyid_year` is of class integer.
- Combine `ppp_data_level` and `cpi_data_level` to a single `data_level` column (making sure that they are identical). 
- Only include the following columns in the final table; `country_code`, `surveyid_year`, `survey_acronym`, `data_level`  and `svy_mean_ppp`. **EDIT:** The table should also include the `survey_id` column. 

A single `data_level` column makes it much easier to merge with the national accounts data down the road. 

I'm not too familiar with the drake plan, so if for some reason we also need to store the svy_lcu_mean, cpi and ppp in the table to check what has changed, that's fine with me. But the `svy_mean_ppp` is the only column we actually need for the reference year pipeline. 

Also remember to call `deflate_welfare_mean()` in `wbpip` for the deflation. 

Thanks,
Aleksander

**Comment by randrescastaneda** [comment]
HI @Aeilert, 

I just created the `db_create_dsm_table` and a couple of other functions. you can see them in the branch [add_dsm_create_table](https://github.com/PIP-Technical-Team/pipdm/tree/add_dsm_create_table). I created a pull request and then closed it because I realized it is better to talk about these functions first before merging them. 

Let's talk. 
Best.

**Comment by Aeilert** [comment]
Closed with #29 and #33
